import { createContext, useContext, useEffect, useMemo } from 'react';

const UIContext = createContext(null);

export const UIProvider = ({ children }) => {
  useEffect(() => {
    document.documentElement.dir = 'ltr';
    document.documentElement.lang = 'en';
    document.documentElement.classList.add('dark');
  }, []);

  const value = useMemo(() => ({
    locale: 'en',
    theme: 'dark',
    t: (key) => translations[key] ?? key,
  }), []);

  return (
    <UIContext.Provider value={value}>{children}</UIContext.Provider>
  );
};

export const useUI = () => {
  const ctx = useContext(UIContext);
  if (!ctx) throw new Error('useUI must be used within UIProvider');
  return ctx;
};

const translations = {
  // Nav
  nav_home: 'Home',
  nav_services: 'Services',
  nav_portfolio: 'Portfolio',
  nav_about: 'About',
  nav_contact: 'Contact',
  cta_get_started: 'Get Started',

  // Hero
  badge: 'Innovative Software & AI Solutions',
  hero_title_1: 'Transforming Ideas',
  hero_title_2: 'Into Digital Reality',
  hero_sub: 'We specialize in cutting-edge software development and AI solutions that drive innovation, streamline operations, and accelerate your business growth.',
  hero_btn_primary: 'Start Your Project',
  hero_btn_secondary: 'View Our Work',
  hero_pill_software: 'Custom Software',
  hero_pill_ai: 'AI & Machine Learning',
  hero_pill_automation: 'Process Automation',

  // Services
  services_badge: 'Our Services',
  services_title: 'Comprehensive Tech Solutions',
  services_subtitle: 'From concept to deployment, we provide end-to-end technology services that drive innovation and deliver measurable business results.',
  service_1_title: 'Custom Software Development',
  service_1_desc: 'Tailored software solutions built with modern technologies to meet your specific business requirements and scale with your growth.',
  service_1_f1: 'Web Applications',
  service_1_f2: 'Desktop Software',
  service_1_f3: 'API Development',
  service_1_f4: 'System Integration',
  service_2_title: 'AI & Machine Learning',
  service_2_desc: 'Leverage the power of artificial intelligence to automate processes, gain insights, and create intelligent applications.',
  service_2_f1: 'Predictive Analytics',
  service_2_f2: 'Natural Language Processing',
  service_2_f3: 'Computer Vision',
  service_2_f4: 'Chatbots & AI Assistants',
  service_3_title: 'Mobile App Development',
  service_3_desc: 'Native and cross-platform mobile applications that deliver exceptional user experiences on iOS and Android.',
  service_3_f1: 'iOS Development',
  service_3_f2: 'Android Development',
  service_3_f3: 'React Native',
  service_3_f4: 'Flutter',
  service_4_title: 'Cloud Solutions',
  service_4_desc: 'Scalable cloud infrastructure and migration services to optimize performance, security, and cost-effectiveness.',
  service_4_f1: 'AWS/Azure/GCP',
  service_4_f2: 'Cloud Migration',
  service_4_f3: 'DevOps',
  service_4_f4: 'Microservices',
  service_5_title: 'Data Engineering',
  service_5_desc: 'Transform raw data into actionable insights with robust data pipelines, warehouses, and analytics solutions.',
  service_5_f1: 'Data Pipelines',
  service_5_f2: 'Data Warehousing',
  service_5_f3: 'ETL Processes',
  service_5_f4: 'Real-time Analytics',
  service_6_title: 'Cybersecurity Solutions',
  service_6_desc: 'Comprehensive security services to protect your digital assets and ensure compliance with industry standards.',
  service_6_f1: 'Security Audits',
  service_6_f2: 'Penetration Testing',
  service_6_f3: 'Compliance',
  service_6_f4: 'Security Training',
  learn_more: 'Learn More',
  process_title: 'Our Development Process',
  process_1_title: 'Discovery',
  process_1_desc: 'Understanding your needs',
  process_2_title: 'Design',
  process_2_desc: 'Creating the blueprint',
  process_3_title: 'Develop',
  process_3_desc: 'Building the solution',
  process_4_title: 'Deploy',
  process_4_desc: 'Launching your project',

  // Portfolio
  portfolio_badge: 'Our Work',
  portfolio_title_1: 'Featured',
  portfolio_title_2: 'Projects',
  portfolio_subtitle: 'Discover how we\'ve helped businesses transform their operations with innovative software solutions and AI-powered applications.',
  portfolio_featured: 'Featured Solutions',
  portfolio_more: 'More Projects',
  view_details: 'View Details',
  portfolio_cta_title: 'Ready to Start Your Project?',
  portfolio_cta_desc: 'Let\'s discuss how we can bring your vision to life with cutting-edge technology.',
  portfolio_cta_btn: 'Get Started Today',
  project_1_title: 'AI-Powered Analytics Dashboard',
  project_1_cat: 'AI & Data Science',
  project_1_desc: 'Comprehensive analytics platform with machine learning insights for e-commerce businesses, featuring predictive analytics and real-time data visualization.',
  project_2_title: 'Smart Healthcare Management System',
  project_2_cat: 'Healthcare Tech',
  project_2_desc: 'Complete hospital management solution with patient tracking, appointment scheduling, and AI-assisted diagnosis support.',
  project_3_title: 'Fintech Mobile Application',
  project_3_cat: 'Financial Technology',
  project_3_desc: 'Secure mobile banking app with biometric authentication, real-time transactions, and AI-powered financial insights.',
  project_4_title: 'E-commerce Automation Platform',
  project_4_cat: 'E-commerce',
  project_4_desc: 'Automated inventory management and order processing system with AI-powered demand forecasting.',
  project_5_title: 'IoT Smart City Solution',
  project_5_cat: 'IoT & Smart Systems',
  project_5_desc: 'Comprehensive smart city platform managing traffic, utilities, and environmental monitoring through IoT sensors.',
  project_6_title: 'Educational AI Tutor Platform',
  project_6_cat: 'EdTech',
  project_6_desc: 'Personalized learning platform with AI tutors, adaptive assessments, and progress tracking for students.',

  // About
  about_badge: 'About ETQAN',
  about_title_1: 'Building the',
  about_title_2: 'Future',
  about_title_3: 'Together',
  about_subtitle: 'We are a passionate team of developers, designers, and AI specialists committed to transforming businesses through innovative technology solutions.',
  stat_projects: 'Projects Delivered',
  stat_clients: 'Happy Clients',
  stat_years: 'Years Experience',
  stat_tech: 'Technologies',
  mission_title: 'Our Mission',
  mission_desc: 'To empower businesses with cutting-edge software solutions and AI technologies that drive growth, efficiency, and innovation. We believe in creating technology that not only solves today\'s challenges but also prepares organizations for tomorrow\'s opportunities.',
  vision_title: 'Our Vision',
  vision_desc: 'To be the leading technology partner for businesses seeking digital transformation. We envision a future where AI and intelligent software solutions seamlessly integrate into every aspect of business operations, creating unprecedented value and possibilities.',
  values_title: 'Our Core Values',
  value_1_title: 'Innovation First',
  value_1_desc: 'We embrace cutting-edge technologies and creative solutions to solve complex problems and drive digital transformation.',
  value_2_title: 'Quality Assurance',
  value_2_desc: 'Every line of code is crafted with precision, tested thoroughly, and built to last with industry best practices.',
  value_3_title: 'Client-Centric',
  value_3_desc: 'Your success is our mission. We work closely with you to understand your needs and exceed expectations.',
  value_4_title: 'Scalable Solutions',
  value_4_desc: 'We build systems that grow with your business, ensuring long-term value and adaptability to future needs.',
  team_title: 'Meet Our Team',
  team_1_name: 'Islam Badran',
  team_1_role: 'CEO, Co\u2011Founder & Software Engineer',
  team_1_expertise: 'Full\u2011Stack Engineering, Architecture, AI Integrations',
  team_1_bio: 'Co\u2011founder leading product and engineering. Focused on building scalable, reliable systems.',
  team_2_name: 'Khaled Sakr',
  team_2_role: 'CEO, Co\u2011Founder & Software Engineer',
  team_2_expertise: 'Backend Systems, Cloud, DevOps',
  team_2_bio: 'Co\u2011founder driving technical delivery and platform reliability.',
  team_3_name: 'Mohamed Abozaid',
  team_3_role: 'CEO, Co\u2011Founder & Marketing Manager',
  team_3_expertise: 'Go\u2011to\u2011Market, Brand, Growth Marketing',
  team_3_bio: 'Co\u2011founder owning brand, positioning, and demand generation.',
  about_cta_title: 'Ready to Work Together?',
  about_cta_desc: 'Let\'s discuss how our expertise can help transform your business with innovative technology solutions.',
  about_cta_btn: 'Start a Conversation',

  // Contact
  contact_badge: 'Get In Touch',
  contact_title_1: 'Let\'s Start Your',
  contact_title_2: 'Project',
  contact_subtitle: 'Ready to transform your business with cutting-edge technology? We\'re here to help you every step of the way.',
  contact_form_title: 'Send us a message',
  contact_first_name: 'First Name',
  contact_last_name: 'Last Name',
  contact_email: 'Email Address',
  contact_company: 'Company (Optional)',
  contact_project_type: 'Project Type',
  contact_select_service: 'Select a service',
  contact_web_dev: 'Web Development',
  contact_mobile_app: 'Mobile App Development',
  contact_ai_ml: 'AI & Machine Learning',
  contact_cloud: 'Cloud Solutions',
  contact_data: 'Data Engineering',
  contact_security: 'Cybersecurity',
  contact_consultation: 'Consultation',
  contact_other: 'Other',
  contact_budget: 'Project Budget',
  contact_select_budget: 'Select budget range',
  contact_budget_1: 'Under $10,000',
  contact_budget_2: '$10,000 - $25,000',
  contact_budget_3: '$25,000 - $50,000',
  contact_budget_4: '$50,000 - $100,000',
  contact_budget_5: 'Over $100,000',
  contact_description: 'Project Description',
  contact_placeholder: 'Tell us about your project requirements, goals, and timeline...',
  contact_send: 'Send Message',
  contact_info_title: 'Get in touch',
  contact_info_subtitle: 'We\'d love to hear from you. Choose the most convenient way to reach out, and we\'ll get back to you as soon as possible.',
  contact_email_title: 'Email Us',
  contact_email_detail: 'hello@etqan.dev',
  contact_email_desc: 'Send us an email anytime',
  contact_phone_title: 'Call Us',
  contact_phone_detail: '+1 (555) 123-4567',
  contact_phone_desc: 'Mon-Fri from 8am to 6pm',
  contact_visit_title: 'Visit Us',
  contact_visit_detail: '123 Tech Street, Digital City',
  contact_visit_desc: 'Come say hello at our office',
  contact_response_title: 'Response Time',
  contact_response_detail: '< 24 hours',
  contact_response_desc: 'We respond quickly to all inquiries',
  faq_title: 'Frequently Asked Questions',
  faq_1_q: 'How long does a typical project take?',
  faq_1_a: 'Project timelines vary from 2-12 weeks depending on complexity and scope.',
  faq_2_q: 'Do you provide ongoing support?',
  faq_2_a: 'Yes, we offer comprehensive maintenance and support packages.',
  faq_3_q: 'Can you work with existing systems?',
  faq_3_a: 'Absolutely! We specialize in integration and system modernization.',
  follow_us: 'Follow Us',

  // Footer
  footer_desc: 'Transforming businesses through innovative software solutions and AI technologies. We build the future, one line of code at a time.',
  footer_services: 'Services',
  footer_company: 'Company',
  footer_resources: 'Resources',
  footer_about_us: 'About Us',
  footer_our_team: 'Our Team',
  footer_careers: 'Careers',
  footer_blog: 'Blog',
  footer_case_studies: 'Case Studies',
  footer_contact: 'Contact',
  footer_docs: 'Documentation',
  footer_api: 'API Reference',
  footer_support: 'Support Center',
  footer_community: 'Community',
  footer_partners: 'Partners',
  footer_privacy: 'Privacy Policy',
  footer_follow: 'Follow Us',
  footer_newsletter_title: 'Stay Updated',
  footer_newsletter_desc: 'Get the latest news about technology trends and our services.',
  footer_newsletter_placeholder: 'Enter your email',
  footer_subscribe: 'Subscribe',
  footer_copyright: '\u00a9 2024 ETQAN. All rights reserved.',
  footer_terms: 'Terms of Service',
  footer_privacy_link: 'Privacy Policy',
};
